language: java
jdk: 
  - oraclejdk7

env:
  global:
    - secure: "uj32149LhL/Ns/Oy4311/J98a9N+JyhLIzU1RM8PQQiS5vIMx9CrnQU5xbYjOIm/jMjTpfuUicgk5Lq8q0oh6Fs7d2nSoZLUngjt5wS4OovtQpZfIdB46iIKakcO8xN2WUcYz2IOpYizyKooaOK30DgtOmxDMH6b6F2KfZTflLs="
  matrix:
  # - ANDROID_TARGET=android-8   ANDROID_SDKS=android-8,build-tools-17.0.0            ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi
  # - ANDROID_TARGET=android-10  ANDROID_SDKS=android-10,build-tools-17.0.0,sysimg-10 ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi
  # - ANDROID_TARGET=android-15  ANDROID_SDKS=android-15,build-tools-17.0.0,sysimg-15 ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi-v7a
  - ANDROID_TARGET=android-17  ANDROID_SDKS=android-17,build-tools-17.0.0,sysimg-17 ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi-v7a
before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar xzf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # Install required Android components.
  - android update sdk --filter platform-tools,android-16,extra-android-support,$ANDROID_SDKS --no-ui --force

  - gradle -PmyToken=$DEPLOY_GATE_API_KEY -q assemble

script:
  - gradle check > build.out
  - gradle -PmyToken=$DEPLOY_GATE_API_KEY build

after_failure: 
  - cat build.out

after_success:
  - gradle -PmyToken=$DEPLOY_GATE_API_KEY uploadDeployGate
