language: java
jdk: 
  - oraclejdk7

env:
  matrix:
  # - ANDROID_TARGET=android-8   ANDROID_SDKS=android-8,build-tools-17.0.0            ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi
  # - ANDROID_TARGET=android-10  ANDROID_SDKS=android-10,build-tools-17.0.0,sysimg-10 ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi
  # - ANDROID_TARGET=android-15  ANDROID_SDKS=android-15,build-tools-17.0.0,sysimg-15 ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi-v7a
  - ANDROID_TARGET=android-17  ANDROID_SDKS=android-17,build-tools-17.0.0,sysimg-17 ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi-v7a
before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar xzf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # Install required Android components.
  - android update sdk --filter platform-tools,android-16,extra-android-support,$ANDROID_SDKS --no-ui --force

  # - gradle -q assemble
  - secure: "dcpA/MFn0uMXV2vX86hIPCnZDKk2aR5YCyJeyANTZaVLBPblyqvKIePXOeXCB+74y6pdtEwlU42vdGC7d67FY4mOBlJ/vOZyjjvB3sCtI5pvIq2CwFWhQyGT3Qo7ZPWDAucoyISroBoTpp/7pCUt6rWB1kHKtO2+V2a9VTRLFjU="

script:
  - gradle check > build.out
  # - gradle build
  - secure: "rnPcyREp1fvFgYIR7iphVGT9FTJd7oQMCsESRzgWkTKRcFTOinvpRg+KWv9dNUH3UgpOHGhIOfRfkC2WlNShVefEtnmdku0gV2LvRDTHuSyeBMi5ii7sycOq2hnhF3vgQpL01ecWOM19fS8c8/GjrEtCX5b6ERcrwv4dXr1C+Y4="

after_failure: 
  - cat build.out

after_success:
  # - gradle uploadDeployGate
  - secure: "QfCe97A7GAkT/838b76TgkokUci79quCy03HHW7EubDX8k0Ff0ckYmFUP0Wua6E8zn9aulQSeFwvAHFfb067ZzTqiRXDABhFd2OJIL9RI+QkfeOgk3NwU311yLW749aRdJj85eNuycOJRUMtMJ8PqekdF93BOsn+gI/oSaHGpyw="
